### ISSUE TITLE
Integration with gin problem

### ISSUE THREAD

**Issue by kockok** [99designs/gqlgen#1217]
### What happened?
I was following [this guide](https://gqlgen.com/recipes/gin/), however, there're compiler issues raised.
![Screenshot 2020-06-16 at 12 54 12 AM](https://user-images.githubusercontent.com/232541/84685458-ea45e780-af6c-11ea-8835-e134968e3501.png)

### What did you expect?

I expect no compiler issue raised.

###My solution:

I had to use alias from the generated go file so as to kick away those compiler issues.
![Screenshot 2020-06-16 at 1 06 14 AM](https://user-images.githubusercontent.com/232541/84686157-0a29db00-af6e-11ea-9562-099d3cb44be1.png)

Just wondering if my approach is correct.

### versions
the latest stable versions.

**Comment by Lilahamstern** [comment]
Could you please **provide more information**. 
* **What error does your imports give.**
* **Instead of pictures it would be easier to have a code example.** 

Extra:
You can import a package without its qualifier with `.` as the importSpec
Read more about import declarations on [golang.org](https://golang.org/ref/spec#Import_declarations)
