### ISSUE TITLE
how to get sub query params

### ISSUE THREAD

**Issue by delsoul6104** [99designs/gqlgen#1470]
how can i get sub query params
ex：schema like
`
query {
    test (name:"sport"){
          future_test(num: 23)
          current{
            name
            date
            score
            }
    		  }
    }
}
`
query.resolvers.go generate 
`
func (r *queryResolver) Test(ctx context.Context, name string) (*model.Test, error) {
}
`
in this func,how can i get num value

thanks~~~~~~~~~

**Comment by MichaelJCompton** [comment]
Hi, thanks for getting in touch.

Seems like you want to do something like look ahead in the `Test` function to see what the actual query was so that you can do some pre-fetching or limit a DB query or something.  Is that right?

If that's so, you can use https://gqlgen.com/reference/field-collection/
