### ISSUE TITLE
How do you get stats regarding which types/queries/mutations are used?

### ISSUE THREAD

**Issue by ngrilly** [99designs/gqlgen#1530]
How do you get stats regarding which types/queries/mutations are used?

With traditional RPC or REST APIs over HTTP, you can have quite good stats about which endpoints are used by just using the HTTP request log produced by the web server.

How do you do it with gqlgen?

**Comment by karthikraobr** [comment]
Have you had a look at https://github.com/99designs/gqlgen-contrib/blob/master/gqlopentracing/tracer.go.
For e.g. You could increment your Prometheus counter inside the `InterceptOperation` to get an idea of how many times each query/mutation is invoked. There might be better ways of doing this, but this has worked well for us.

**Comment by leavengood** [comment]
You can create a `graphql.FieldMiddleware` and then get the field context:

```go
fctx := graphql.GetFieldContext(ctx)
```

Which you can then check `fctx.Object` for a "Query" or "Mutation" and also look at the `fctx.Field.Name` (which is the query or mutation name) and arguments (`fctx.Args`), and then log something, or call a metrics service.

Just keep in mind this middleware gets called for all resolver methods, which is why you need to gate it by looking at the object, though if you also care about other resolvers you could log stats on those too.

**Comment by lwc** [comment]
Both good answers 🙌  check out the [debug tracer](https://github.com/99designs/gqlgen/blob/master/graphql/handler/debug/tracer.go) for more.
