### ISSUE TITLE
Are there any hooks before resolvers?

### ISSUE THREAD

**Issue by RobertoOrtis** [99designs/gqlgen#1577]
Hi,

I would like to implement authorization routes by intercepting the path before the resolver is called.

I already have implemented authorization by using a middleware and checking if the user has valid credentials; however, I have to check their validity inside every resolver because there are routes that don't require credentials. So, I would like to intercept every call to each resolver and decide whether to grant access depending on the GraphQL path being called.

**Comment by diep-it-dn** [comment]
I think you my repo can help you:
https://github.com/diep-it-dn/fullstack-go-angular

**Comment by wilhelmeek** [comment]
@RobertoOrtis you can use directives to achieve this. The [docs have a pretty similar example](https://gqlgen.com/reference/directives/#implement-the-directive) to what you need.

Alternatively you could use [AroundFields](https://github.com/99designs/gqlgen/blob/master/graphql/handler/server.go#L73) if you'd prefer. Using `graphql.GetFieldContext(ctx).IsResolver` within that middleware should tell you whether you're wrapping a resolver. 

I see this issue is quite old, so hopefully you've been able to get something working in the mean time.

**Comment by RobertoOrtis** [comment]
> @RobertoOrtis you can use field directives to achieve this. The [docs have a pretty similar example](https://gqlgen.com/reference/directives/#implement-the-directive) to what you need.
> 
> Alternatively you could use [AroundFields](https://github.com/99designs/gqlgen/blob/master/graphql/handler/server.go#L73) if you'd prefer a more global approach. Using `graphql.GetFieldContext(ctx).IsResolver` within that middleware should tell you whether you're wrapping a resolver. 
> 
> I see this issue is quite old, so hopefully you've been able to get something working in the mean time.

Great thanks, I think the example in the docs will be enough 👍🏻
