### ISSUE TITLE
Flaky Websocket test

### ISSUE THREAD

**Issue by StevenACoffman** [99designs/gqlgen#2193]
### What happened?
Some test runs get this error:
```
--- FAIL: TestSubscriptions (2.02s)
    --- FAIL: TestSubscriptions/websocket_gets_errors (2.01s)
        subscription_test.go:192: 
            	Error Trace:	subscription_test.go:192
            	Error:      	Not equal: 
            	            	expected: 8
            	            	actual  : 3
            	Test:       	TestSubscriptions/websocket_gets_errors
```
Re-running causes them to pass.

### What did you expect?

Consistent Test results

**Comment by alexvelea** [comment]
I've been trying to reproduce the behavior without any success using.
```
go test -count=500 -run TestSubscriptions ./codegen/testserver/singlefile/
go test -count=500 -run TestSubscriptions ./codegen/testserver/followschema/
```

Prior to this, I've run `go generate ./...` in the root folder.

I've seen that no updates have been made to the test file. 
Is there a chance that it was fixed in one of the dependencies?
Are you still able to reproduce the behaviour?

**Comment by StevenACoffman** [comment]
I believe this issue is resolved. It turns out there were several causes, and several incremental fixes. I left this issue open to see if there were still more problems, but I think we can safely close it now.
