### ISSUE TITLE
Incorrect response when errors occurred

### ISSUE THREAD

**Issue by atzedus** [99designs/gqlgen#2470]
### What happened?
When querying multiple fields at once and at least one of it returns error, then whole response become null with no any description where it `null` is.

### What did you expect?
List of errors and `data` with fields name queried.

### Minimal graphql.schema and models to reproduce

Schema:

```graphql
type Query {
    Kids: [ID!]
    Martials: [ID!]
}
```

Query:

```graphql
query Lists {
  	Kids
  	Martials
}
```

Result: 

```json
{
  "errors": [
    {
      "message": "some error",
      "path": [
        "Kids"
      ]
    }
  ],
  "data": null
}
```

What expected?: 

```json
{
  "errors": [
    {
      "message": "some error",
      "path": [
        "Kids"
      ]
    }
  ],
  "data": {
       "Kids": null,
       "Martials": [1, 2, 3, 4]
  }
}
```

### versions
 - `go run github.com/99designs/gqlgen v.0.17.22`?
 - `go 1.19`?

P.S. I will send pull request to fix this soon.

**Comment by jwatte** [comment]
This is a major behavior change, breaking a lot of existing code.
Making this part of a bugfix version release is quite surprising.

**Comment by pksieminski** [comment]
@atzedus are you sure that behaviour that you described in your issue is correct for the schema you listed?

I rolled back gqlgen to version `v0.17.22` and tested it with your schema:
```graphql
extend type Query {
  Kids: [ID!]
  Martials: [ID!]
}
```
Returned `nil, errors.New("some error")` in Kids resolver and received this response:
```json
{
  "errors": [
    {
      "message": "some error",
      "path": [
        "Kids"
      ],
    }
  ],
  "data": {
    "Kids": null,
    "Martials": ["1", "2", "3", "4"]
  }
}
```

To receive result as claimed in your issue, Kids list would have to be Non-Null type as follows for `KidsNN`:
```graphql
extend type Query {
  Kids: [ID!]
  KidsNN: [ID!]!
  Martials: [ID!]
}
```
Now with same `nil, errors.New("some error")` return value for KidsNN resolver, you will receive response:
```json
{
  "errors": [
    {
      "message": "some error",
      "path": [
        "Kids"
      ],
    },
    {
      "message": "some error",
      "path": [
        "KidsNN"
      ],
    }
  ],
  "data": null
}
```

And above behaviour is correct according to Graphql specification:
- Since Kids list type is not Non-Null, in case of null value and error, it propagates it at most up to the list
- Since KidsNN list type is Non-Null, in case of null value and error, it propagates further up to data root field, since KidsNN is Non-Null and returning it null would break schema contract and work against GraphQL spec

According to this [spec](http://spec.graphql.org/draft/#sec-Handling-Field-Errors) previous behaviour was correct:
> If a List type wraps a Non-Null type, and one of the elements of that list resolves to null, then the entire list must resolve to null. If the List type is also wrapped in a Non-Null, the field error continues to propagate upwards.

> If all fields from the root of the request to the source of the field error return Non-Null types, then the "data" entry in the response should be null.

Based on the above points I believe that https://github.com/99designs/gqlgen/pull/2471 should be reverted.
