### ISSUE TITLE
Support for UUID type in ID scalars

### ISSUE THREAD

**Issue by vadimvera** [99designs/gqlgen#3013]
I would like to propose an enhancement regarding the support for Universally Unique Identifier (UUID) types within the `ID` scalar.

Currently, `gqlgen` [supports several types](https://github.com/99designs/gqlgen/blob/master/graphql/id.go) for the `ID` scalar. However, with the increasing popularity of UUIDs for unique identifiers in modern applications, it would be beneficial to have _native_ support for UUIDs within the `ID` scalar as well.

This will provide developers with more flexibility in designing GraphQL schemas, especially for applications where UUIDs are the preferred and/or default choice for unique identifiers.

**Comment by it512** [comment]
https://gqlgen.com/reference/scalars/

**Comment by macnibblet** [comment]
I think this is going to be complicated to support because there are too many UUID libraries in the wild. 

Which one will we decide to support in this library? The current approach is flexible enough in my opinon, and as @it512 pointed out, it's already easily supported.

**Comment by itd-jt** [comment]
Hi @macnibblet, @it512,

I have a question regarding the implementation of custom UUID scalars in our GraphQL application.

We are considering using the suggested solution of a custom UUID scalar for our "id" fields. However, we are concerned about potential issues that might arise if we change the type of these fields from "ID" to our custom UUID scalar type.

According to the [GraphQL Best Practices](https://graphql.org/learn/global-object-identification/), the Node interface should use the "ID" scalar:

```
# An object with a Globally Unique ID
interface Node {
  # The ID of the object.
  id: ID!
}
```

Additionally, [Relay](https://relay.dev/docs/debugging/disallowed-id-types-error/) appears to require the "ID" type as well.

Could you please clarify whether it is officially supported or recommended to use a custom scalar instead of "ID" for the id field? If not, what steps need to be taken to ensure safe and correct implementation?

Thank you for your assistance!

Regards,
Jakob
