### ISSUE TITLE
HTTP handler should not allow mutations on GET requests

### ISSUE THREAD

**Issue by edsrzf** [99designs/gqlgen#317]
The HTTP handler should not allow mutations on HTTP GET requests. Or at least make it configurable. This is asking for a CSRF vulnerability.

Alternatively, don't allow running queries on GET requests at all. GitHub's GraphQL API, for example, does the standard introspection query when you send it a GET request.

**Comment by vektah** [comment]
Yeah, I have the same concerns. 

The HTTP transport is really under-specified but I think GET is part of the spec - https://graphql.org/learn/serving-over-http/

The whole handler package probably needs a refactor, but yeah get should probably be configurable at least to disable it. Maybe even defaulted off. 

I don't think peering into the graphql query is the way to go though.

**Comment by yamitzky** [comment]
Disabling GET request is not a solution to CSRF, though GET is risky because Google bot may access it and cause mutation request.

I think,

1. `mutation` by GET request should be disabled.
2. `query` by GET request should be accepted.
3. CSRF attacks should be protected by other ways, e.g. CSRF token, because the attack can be done by POST request.

c.f. [Apollo's policy](https://www.apollographql.com/docs/apollo-server/requests.html)
