### ISSUE TITLE
gqlgen with go 1.23 fails with "unable to find type" errors

### ISSUE THREAD

**Issue by kjamieson-sdm** [99designs/gqlgen#3272]
### What happened?

Using even the latest revision of gqlgen with go 1.23 is failing to generate with `merging type systems failed: unable to build object definition: unable to find type` errors (specifying an arbitrarily different model every failure).

For example:

```
~ $ git clone https://github.com/99designs/gqlgen     
gqlgen $ cd gqlgen
gqlgen $ go build
graphql $ ~/gqlgen/gqlgen generate
merging type systems failed: unable to build object definition: unable to find type: github.com/strongdm/web/pkg/graphql/graph/model.TestAction
```

The only workaround we've found is to explicitly build gqlgen with go 1.23, i.e.:
```
gqlgen $ sed -i '' -e 's/go 1.22.5/go 1.23.0/' go.mod
gqlgen $ go build
graphql $ ~/gqlgen/gqlgen generate
graphql $
```

Are there any plans to update gqlgen to go 1.23 in the near future?

### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.49-dev (f154d99d6dde67cc6f81cb03cb7746a2d6934926)
 - `go version`? go version go1.23.0 darwin/arm64

**Comment by StevenACoffman** [comment]
I am having trouble reproducing this problem. We have a github action that tests fmt and generate for Go 1.22 and Go 1.23:
https://github.com/99designs/gqlgen/actions/runs/10852649106/job/30119164164

Your error message indicates that the problem is not in gqlgen, but in the `strongdm/web` repository:
```
merging type systems failed: unable to build object definition: unable to find type: github.com/strongdm/web/pkg/graphql/graph/model.TestAction
```

But I do not have access to this repository, so I am having trouble figuring out what the problem here is.
