### ISSUE TITLE
Bind a model to a protobuf 

### ISSUE THREAD

**Issue by macnibblet** [99designs/gqlgen#3442]
### What happened?
It works, but with vet errors as we are copying the lock value which causes issues with go vet and linters

### What did you expect?
I shouldn't see the following errors

```
return copies lock value: DocumentToContent contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
```

### Minimal graphql.schema and models to reproduce
```graphql
input Foo @goModel(model: "<insert protobuf struct path>") {
  id: String!
}
```

```protobuf
message Foo {
  string id = 1;
}
```

**Comment by StevenACoffman** [comment]
If you try to pass a proto by value you will get a govet error complaining about copylocks

This is because protos use a govet trick to prevent you from accidentally making a shallow copy of the proto when you were expecting a deep copy. This is explained in this [StackOverFlow Post] (https://stackoverflow.com/questions/64183794/why-do-the-go-generated-protobuf-files-contain-mutex-locks).

I think the reason protos have that defense mechanism is because when a struct is passed by value in GoLang the members could either be a shallow or deep copy. See [this article](https://echorand.me/posts/go-values-references-etc/). So in general if you pass a copy of a proto it will be a shallow copy so if you modify it the original will be modified. In particular if the proto contains a map or nested protos which are stored as pointers then you could modify the original proto.

I think the copylocks are there to prevent you from accidentally doing a copy and thinking its a deep copy. Passing protos by pointer makes it clear its a pointer and not a copy.

For your purposes in gqlgen, you can solve this in several ways right now:
+ make your input model be a struct that contains a pointer to the actual protobuf struct
+ make your input model here optional so it will be a pointer

A feature request might be that the `@goModel` directive add an optional parameter `pointer` that could be set to `true` so generated code will use a pointer to the type rather than the type itself. If that's what you want, then I think that's a great idea, and I would welcome a PR that made that change.

**Comment by StevenACoffman** [comment]
Hey, if you want to open a feature request issue asking for the `@goModel` directive to add an optional parameter pointer, please do so.

Even better, please open a PR to add it. Thanks!
