### ISSUE TITLE
Issue Using Fragments on Union Types

### ISSUE THREAD

**Issue by bannzai** [99designs/gqlgen#399]
#### Response JSON
```graphql
{
  "data": {
    "Q": {
      "__typename": "A",
      "a": "1"
    }
  }
}
```

#### Actual Response JSON
```graphql
{
  "data": {
    "Q": {
      "__typename": "A"
    }
  }
}
```

#### schema
```graphql
type Query {
  Q(): U!
}

type A {
 a: String!
}
type B {
 b: Boolean!
}

union U = A | B
```

#### Query 
```graphql
query {
  Q {
    __typename
    ...F
  }
}

fragment F on U {
  __typename
   ... on A {
    a
  }
  ... on B {
    b
  }
}
```

#### Resolver

```go
func (r *queryResolver) Q(ctx context.Context) (model.U, error) {
	return model.A{A: "1"}, nil
}
```

### Description
I want to get for *Expected Behaviour* json when client request query. 
But I can't receive *Expected Behaviour* json. So, It is not exists `"a": "1"` json field.
Please tell me if there is a solution on this.

**Comment by mbranch** [comment]
I ran into this as well, and I think the root issue has to do with fragment usage. The above query, with the fragment removed, **does** seem to work:

```graphql
query {
  Q {
    __typename
   ... on A {
	    a
	  }
	  ... on B {
	    b
	  }
  }
}
```

**Comment by mbranch** [comment]
I've found that issue can be resolved (though incorrectly) by omitting the following lines.

https://github.com/99designs/gqlgen/blob/5c870a489da3eecd57b4152f0501b65cd682f4af/graphql/exec.go#L62-L64

It seems to me that a fragment on a union isn't truly supported.

This is a very superficial look into this that may help someone with more knowledge understand the issue quickly. When I have some time, I may look into it further as we really like this tool so far, but this bug is a showstopper unfortunately.

**Comment by mbranch** [comment]
Following up on this, I see a related remark in pull request https://github.com/99designs/gqlgen/pull/335:

> RFC probably doesn't handle the case where the interface is not generated, but the models are, what should happen there?
> - This case is actually kind of insane, so upon further thought let's not handle it.

@lwc Would you mind weighing-in on this issue, your comment seems to suggest there's something fundamentally wrong with returning a list of heterogeneous types without an common interface. I don't see why, but maybe I'm missing something.
