### ISSUE TITLE
Directive on FIELD_DEFINITION returns whole object null

### ISSUE THREAD

**Issue by sandeepone** [99designs/gqlgen#431]
### Expected Behaviour
Directive on field makes whole object to null instead of the ```done``` field. The todo example in the repo.
```
    done: Boolean! @hasRole(role: OWNER) # only the owner can see if a todo is done
```

Only the ```done``` field needs to return null
```
"todo": {
id: 1
text: "Somebody else's todo"
done: null
}
```

### Actual Behavior

Whole todo returns null
```
"todo": null
```

### Minimal graphql.schema and models to reproduce
https://github.com/99designs/gqlgen/blob/02a1935255fadced7f122dff7f2a9f54546c9d61/example/todo/schema.graphql#L20

**Comment by vektah** [comment]
This happens because `done` is marked as `Not Null` in the schema, so returning a null from the server would lead to runtime issues in the client. Instead the server recursively walks up the tree until it finds something it can set to null, in this case the `todo`.

This is part of the [spec](https://facebook.github.io/graphql/June2018/#sec-Errors-and-Non-Nullability):
> If the result of resolving a field is null (either because the function to resolve the field returned null or because an error occurred), and that field is of a Non-Null type, then a field error is thrown. The error must be added to the "errors" list in the response.
> ...
> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.
