### ISSUE TITLE
schedule for support updating

### ISSUE THREAD

**Issue by FingerLiu** [99designs/gqlgen#485]
When will it support updating schema.graphql?
For now, it seems it does not support updating unless you delete resolver.go manually.
https://gqlgen.com/getting-started/#write-the-resolvers

I want to ask, is this feature WIP? Is there a schedual for this?
the thing gqlgen is really awesome and I really want to use it in production, but without 
support for updating, I can not say it is **production ready.**

**Comment by mathewbyrne** [comment]
Stub generation is not the main output of gqlgen. You can freely run gqlgen multiple times and it will generate you a new server, but currently it will not overwrite the `resolver.go` stubs.  However "updating" your code is as simple as adding the missing resolver methods.  Since this is just an interface, Go will give you very clear direction as to what is missing.

This is a feature we want to implement, but is blocked on some internal refactors to do with how we generate code.  I would consider this feature currently incomplete, and more of an aid during bootstrap.

gqlgen has been used in production for almost a year now and has several confirmed usages in our [production issue](https://github.com/99designs/gqlgen/issues/268).
