### ISSUE TITLE
Add More Detailed Resolver and Configuration Docs

### ISSUE THREAD

**Issue by jwatte** [99designs/gqlgen#546]
I'm reading the docs on Resolvers and Dataloaders.

The docs for Resolver says "bind to a method" and shows some code that uses a go-defined struct with a method name. However, it doesn't tell me what specific rule the generator uses to decide to use the method -- "if the GQL schema name matches a member function, the function is called" might be the rule? If so, if I want a gqlgen-generated model to generate functions for some properties, how do I do that? Or is that only possible with go-defined structs?

The docs for Dataloaders say that `our todo.user resolver looks like this` but if I generate a model from gqlgen, it doesn't generally generate those Resolvers for the structures; just for the Query root. So, how do I get a Resolver for the Todo_user, and what's the rule for how the generator decides to use it? Can I make this happen using gqlgen generated models?

It would be great if the documentation filled in these nuts-and-bolts somewhere.

Actually, it gets more confusing. If I have this:

    type Blah {
      things: [Thing!]!
    }

and I change it to this:

    type Blah {
      things: [Thing!]!
      thingsMatching(s: String!): [Thing!]!
    }

and re-generate and compile, it still compiles, and no interface or function hook is defined where I can implement the resolver for `thingsMatching()`

It feels as if gqlgen really is intended to be used with go-defined structs bound in the `yml` file, and the generated models are some kind of semi-supported afterthought.

But if so, where is the full syntax and functions of the `.yml` file described? I can't find it in the docs.

**Comment by mathewbyrne** [comment]
Yes, I agree that explaining how resolvers are bound and generated is a bit of a gap in our documentation.  It's something we're planning to address before a 1.0 release.

> and re-generate and compile, it still compiles, and no interface or function hook is defined where I can implement the resolver for `thingsMatching()`

You're talking about generated models?  Yes I believe the model generator will currently ignore the arguments and just generate you a field with the correct type.

> It feels as if gqlgen really is intended to be used with go-defined structs bound in the `yml` file, and the generated models are some kind of semi-supported afterthought.

In some ways yes, model generation is intended to get you up and running quickly with compatible types.  I've found model generation really handy for enums and input objects, but over time I find myself binding directly to user defined structs, since they will often have additional presentation or business logic on them.

[Configuration](https://gqlgen.com/config/) describes the shape of the config file.  If you think it's out of date, or has missing descriptions then feel free to point them out or submit a PR.

**Comment by jwatte** [comment]
Thanks for the answer!

Regarding Configuration, that looks like an example file to me. At a minimum, explaining that it represents the sum total of the configurable bits would be clarifying!

**Comment by mathewbyrne** [comment]
> t's also not clear to me whether I can, say, specify `models.Foo.fields.bar.resolver` if I don't specify `models.Foo.model` as a specific type.

True, but also I don't see any reason to think that you couldn't do that. It's not much work to give it a shot!

But I agree the config documentation could be clearer.  So I think this issue should track:

1. Improvements to documentation explaining how gqlgen decides on when it should generate resolvers.
2. Clearer configuration documentation.
