### ISSUE TITLE
Resolve GraphQL Type Names and Descriptions from Go Types

### ISSUE THREAD

**Issue by exfly** [99designs/gqlgen#561]
How can I get gqlphql type name by go type name,  or how can I get the graphql desc

### Expected Behaviour
```
enum ContractPayOrPaidID {
  """
  pay desc
  """
  pay
  """
  get paid desc
  """
  get_paid
  """
  no money desc
  """
  no_money
}
```

Like the enum `ContractPayOrPaidID`, I want to get the GQL type name by go reflect(like  reflect.ValueOf(t).Name() ), but what the name I get is diff from GQL type name. So how can I get gqlphql type name by go type name,  or how can I get the graphql desc? 

This is my code:
```
func schemaDesc(typeNm string, t interface{}) (ret string) {
    v := reflect.ValueOf(t)
    enums := parsedSchema.Types[typeNm]
    switch v.Kind() {
    case reflect.String:
        ret = enums.EnumValues.ForName(v.String()).Description
    case reflect.Ptr:
        e := v.Elem()
        for e.Kind() == reflect.Ptr {
            e = e.Elem()
        }
        ret = enums.EnumValues.ForName(e.String()).Description
    }
    return
}

func SchemaDesc(t interface{}) (ret string) {
    typeN := reflect.ValueOf(t).Name()
    return schemaDesc(typeN, t)
}
```

### Actual Behavior
run:
```
var t ContractPayOrPaidId = "pay"
SchemaDesc(t)

// want: pay desc
// get:    panic
```

### Minimal graphql.schema and models to reproduce

```
enum ContractPayOrPaidID {
  """
  pay desc
  """
  pay
  """
  get paid desc
  """
  get_paid
  """
  no money desc
  """
  no_money
}
```

**Comment by mathewbyrne** [comment]
Currently we don't provide a method for reflecting a GraphQL type name from a Go type.  This might be slightly tricky in our `next` branch since this is no longer a 1:1 mapping, and the same Go type could in theory be mapped to multiple GraphQL types depending on context.

For descriptions, you might have mixed success depending on what you want descriptions for.  The `executionContext` does embed a `ast.Schema` struct, but I do not believe we provide a way to access this from a resolver currently.  If you look at `RequestContext` you can get an AST of the incoming query, which will probably include descriptions.

It would be good to understand your use-case though, so we can decide on whether this is something we want to include in the library.

**Comment by exfly** [comment]
since `next branch since this is no longer a 1:1 mapping, and the same Go type could in theory be mapped to multiple GraphQL types depending on context.`,  I can not use this trick in my code in order to upgrade `gqlgen` easily.
@mathewbyrne Thanks.

**Comment by mathewbyrne** [comment]
I could see some use-cases for this. For example when Collecting Fields it can be important to know all the implementors for a GraphQL type, and is often more convenient to query this by a Go type.  So I think there might be room for a generated static API here. Would be interested to see if this would help any other use-cases.
