### ISSUE TITLE
proposal: panic on receiving null values for non-nullable fields

### ISSUE THREAD

**Issue by ssttevee** [99designs/gqlgen#671]
The current behaviour for handling non-nullable fields does not seem right.

If I wrote the schema to use non-nullable fields, I should have programmed the resolved to return a non-null value. If I failed to do that, that is a programming error and it should not be propagated to the user.

Quoting [Go by Example](https://gobyexample.com/panic), `panic`s should be used "to fail fast on errors that shouldn’t occur during normal operation". Following that logic, a `panic` would be the proper way to handle such an error.

Additionally, `panic`ing would allow for the developer to decide how to handle such cases through the usage of `handler.RecoverFunc`.

Thus, I believe that null values received for non-nullable fields should result in a `panic` instead of a graphql error.

On a side note, having `*time.Time` be checked for `nil` and `IsZero` seems redundant and unecessary.

**Comment by vektah** [comment]
This is pretty well defined behaviour in [the spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors-and-Non-Nullability)

It's optimising for good hi behaviour, if you say not null, typescript puts a not null in its generated client side types and the server is expected to meet it's contract. Even when it's erroring. This lets the clent show the user a good error, instead of hitting a null and crashing there too.

**Comment by ssttevee** [comment]
I don't really see why `panic`ing would change that behaviour?

The problem I'm having is that non-null errors are practically silent from the server's perspective. On several occasions, I didn't find out that there was a problem until I ran into edge cases on the client side.

**Comment by vektah** [comment]
Maybe its a bit of both, panic so it goes through the recover hook (where you can send to your bugtracker), but send a well formed spec-compliant response.
