### ISSUE TITLE
IsZero method usage is problematic

### ISSUE THREAD

**Issue by edsrzf** [99designs/gqlgen#684]
### What happened?

This PR introduced special behavior when a model has an `IsZero` method: https://github.com/99designs/gqlgen/pull/540 (first released in gqlgen 0.8.0)

When `v.IsZero()` returns `true`, the value is treated as `null`: https://github.com/99designs/gqlgen/blob/3e39b57a98fac8d4db1a85e0b998bd83e29fb9c5/codegen/type.gotpl#L59-L68

This happens even when the field is not nullable, which causes an error.

Our concrete use case is that we use this package to model numbers where precision is important, such as monetary values: https://github.com/shopspring/decimal

`decimal.Decimal` has an `IsZero` method and is, by convention, passed by value. Its zero value definitely should not be treated as null.

### What did you expect?

I expected zero to mean zero, as it did in previous gqlgen versions. Not null.

### versions
 - `gqlgen version`? 0.8.3
 - `go version`? go version go1.11.4 darwin/amd64
 - dep or go modules? dep v0.5.0

**Comment by vektah** [comment]
Maybe we should scope this to just time.Time instead.

**Comment by qhenkart** [comment]
@vektah This breaking change hit us as well as we sometimes have zero valued timestamps, I appreciate your response greatly. 

As for scoping this to just time.Time. Go is very particular about nil vs zero/default values with their struct definitions, and it's weird to overpower that. When a zero value time.Time == nil, but surely a zero valued int not nil, and an empty string is not nil. None of these are obvious when the library is taking control of this behavior and embedding it so deeply in the generated code.

I do understand that this would sometimes be useful (like with UUID), but I strongly believe those decisions should be decided by the developer and the use-case and not by the library

**Comment by edsrzf** [comment]
I'm happy to write up a PR to use `IsNull` instead if that's the approach we can agree on.

**Comment by vektah** [comment]
I think a graphql server returning `0000-00-00 00:00:00` to a client is always a bug, it should have returned `null`, and if its a non nullable field it should have been an error. 

Would be happy to to change this logic to `(it.IsTime && it.IsZero) || it.IsNull`

**Comment by qhenkart** [comment]
@vektah I am seeing from your response that zero valued timestamp errors are here to stay. We run a large enterprise app and are slowly migrating over to this library. Our convention with Go timestamps is to set all default timestamps as 0 unix time – with REST, this was an easy approach to avoid having to deal with pointers for every timestamp and much better than Go's default 0000– , but occasionally some slip through the cracks due to human error or a bug or whatever. We need more resiliency for our customers than having an entire request fail because of a missing or ill-formed timestamp, and asking our FE team to update their codebase to expect null timestamps isn't a feasible option for us either.

It would be great if 
1. You allowed custom scalars to have a validation method as well as a un/marshal method that overpowers the new validations we are discussing here. This allows us to validate and handle a timestamp –and other scenarios– in our own way (in this case, we would check if it's zero and convert it to unix zero value, and perhaps send a log to let our team know there is inconsistent data)

2. On field error, it would be great if partial data was still returned for a resolver along with the error message instead of closing the entire resolver

For other people following this thread, a simple solution without having to fork the library is to wrap the time.Time into your own struct, overwriting the IsZero method yourself and adding a custom scalar

something like this will do the trick:
```

type Timestamp struct{ time.Time }

func NewTimestamp(t time.Time) Timestamp {
	return Timestamp{
		Time: t,
	}
}

func (t *Timestamp) IsZero() bool {
	if t.Time.IsZero() {
		// you can handle (or ignore) zero timestamps here yourself in our case, we are simply setting it to unix 0
              t.Time = time.Unix(0, 0)
	}
	return false
}
```

You can follow the documentation to add a simple custom scalar for time. The same solution can be used to handle any case where you need to overwrite the IsZero value to control the resiliency of errors in the generated graphql code
