### ISSUE TITLE
Setting headers based on values in response body?

### ISSUE THREAD

**Issue by debnath** [99designs/gqlgen#729]
### What happened?

I have a hard requirement where I need to set cache-control max-age response headers based on particular values within the response body.  To do this, ideally there would be some way to set a context variable at the resolver level, and then read that value at the handler level and set the max-age response headers accordingly.  

I cannot find anything in the documentation to this effect.  Is this use case possible?  I think I could do it with a middleware, but that gets very complicated as the response structure can be unpredictable as it varies depending on the user query.

### What did you expect?
I was hoping there would be a feature similar to graphql-go's _RootValue_ feature, which allow you to get and set arbitrary RequestContext values.

### versions
 - `gqlgen version`?  dev
 - `go version`? go1.12.1 darwin/amd64
 - dep or go modules? dep

**Comment by mathewbyrne** [comment]
Discussion in #567 is relevant to this.  Basically our supported method for bridging between GraphQL and HTTP is through context and HTTP middleware.  This is because the GraphQL is intended to be transport agnostic, so we do our best to keep HTTP handlers and resolvers segregated.

If you search around a bit more you might find some other related issues as well.
