### ISSUE TITLE
Creating database model for one to many relation

### ISSUE THREAD

**Issue by abdusshakurayon** [99designs/gqlgen#921]
### What happened?
https://gqlgen.com/getting-started/
By following this tutorial, I can create a custom database model of `Todo` which has a single `UserId` as shown in the tutorial
```
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}
```

But what do I need to do then there is multiple `User` for a `Todo`. Something like this,
```
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserIDs []string
}
```

### What did you expect?
I expect gqlgen will support one to many or many to many database relations.

### Minimal graphql.schema and models to reproduce
```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  users: [User!]
}
```
```
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserIDs []string
}
```
### versions
 - `gqlgen version`? 
v0.10.1-dev
 - `go version`?
 go1.13
 - dep or go modules?
go module

**Comment by MChartier** [comment]
I have this same question. I want to update a generated model so that I can generate a lazy resolver for a one-to-many relation, but it's not at all clear how to do this in the docs.

**Comment by DanCharousek** [comment]
I'll leave this here in case someone might run into similar issue:

@MChartier 

> I have this same question. I want to update a generated model so that I can generate a lazy resolver for a one-to-many relation, but it's not at all clear how to do this in the docs.

I was trying to achieve the same. Working with the todo/user demo from the docs I managed to implement the 1:N relation where (Todo belongs to User). I.e. I was able to issue query like this:

```graphql
{
  todos {
    id
    text
    user {
      name
    }
  }
}
```

Then I tried to reverse the relationship. I wanted to get all todos for given user (or collection of users).
I updated the schema for the user to look like this.

```graphql
# user.graphqls (I've split the schema definition into separate files, but it should not play a role here)
type User {
  id: ID!
  name: String!
  todos: [Todo!]! # <--- this is the update a made
}
```

Then I ran the `go generate ./..` and it added a new method and some other definitions to the `user.resolvers.go` file:

```go
func (r *userResolver) Todos(ctx context.Context, obj *model.User) (todos []*model.Todo, err error) {
        // after the generation this method was empty
	for _, todo := range r.todos {
		if todo.UserID == obj.ID {
			todos = append(todos, todo)
		}
	}

	return todos, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

```

And this was enough to get me to the point where I could query the todos of the users:

```graphql
{
  users {
    todos {
      id
      text
    }
  }
}
```

I don't know why, but it did not work at first. I think I must've had overlooked something, because once I ran the `generate` command again, the code described above showed up in the file.

**Comment by abdullahmamunv2** [comment]
any update ?

**Comment by deitrix** [comment]
If you follow the documentation, you'll find that you can override the generated Go model types by creating your own types, and updating the `gqlgen.yml` config to point to those types, either by using `autobind` or through manually mapping the types using `models`. Then, once you run `go generate` again, gqlgen will omit the generated types from `models_gen.go`, instead using your custom types.

gqlgen will expect all fields defined in your schema to be present in some form on your custom Go type. If any field is omitted from the Go type, gqlgen will generate a resolver interface for that type, and will expect you to implement it.

For example, given the schema:
```graphql
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  users: [User!]!
}
```

And the custom Go type:
```go
type Todo struct {
	ID      string
	Text    string
	Done    bool
	UserIDs []string
}
```
Because the `Todo` struct does not contain a `Users` field, gqlgen generates a `TodoResolver`:
```go
type TodoResolver interface {
	Users(ctx context.Context, obj *model.Todo) ([]*model.User, error)
}
```
And will create a `todoResolver` implementation on your `Resolver`:
```go
// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }
```
```go
func (r *todoResolver) Users(ctx context.Context, obj *model.Todo) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented"))
}
```
You can then access the `UserIDs` field on `obj`, and fetch the users lazily. `Users()` will only be called when it is specified in the GraphQL query.

Alternatively, you can attach a method to the custom type itself, and gqlgen will pick up on that, skipping generating a resolver for it.
```go
type Todo struct {
	ID      string
	Text    string
	Done    bool
	UserIDs []string
}

func (t *Todo) Users(ctx context.Context) ([]*User, error) {
	panic(fmt.Errorf("not implemented"))
}
```
