### ISSUE TITLE
How I can pass cookie to response after mutation?

### ISSUE THREAD

**Issue by voodoo-dn** [99designs/gqlgen#932]
Hi. I already read https://github.com/99designs/gqlgen/issues/567, but cant understand how it works.

After mutation(registration) or query(login) I need to pass cookie with authentication token to the response.

How I can do it? Thanks.

**Comment by BitPhinix** [comment]
You might want to take a look at: https://github.com/99designs/gqlgen/issues/567

**Comment by BitPhinix** [comment]
The main problem preventing you from setting cookies is the fact that you can't write headers after you have written data inside the response. Since headers are set using HTTP headers you need to somehow write them before sending back the response to the client. This is exactly what https://github.com/99designs/gqlgen/issues/567#issuecomment-542779271 does using a custom http writer implementation. Hope it helps
