### ISSUE TITLE
How to do authorization(RBAC) when using gqlgen?

### ISSUE THREAD

**Issue by zwl1619** [99designs/gqlgen#936]
How to do authorization(RBAC) when using gqlgen?

**Comment by oshalygin** [comment]
The way we handle it is relatively straightforward and doesn't depend on gqlgen at all.  I'd be open to any other suggestions but basically we add middleware the mux that captures the request context, piecing apart the users JWT, serializing it into a user object and storing it on the request context.  Within the resolver, parse the context key and response accordingly.

I'd actually consider looking at other RBAC patterns from other frameworks/lang implementations because, to me, its independent of graphql/library.

**Comment by JeremyMarshall** [comment]
I was looking for this, so far I have the same where a [JWT token is passed in a header](https://github.com/bythepowerof/gqlgen-kmakeapi/blob/3d88201d7257092ea3949d67fd13938617d0159a/view/http.go#L94)  then decoded. It seems to me that the RBAC rules could be served with GQL - and maybe mutated too. I'll have a go at putting a self contained demo together maybe using [this RBAC library](https://github.com/zpatrick/rbac) - for my needs though, I want to surface kubernetes RBAC
